version: '3'
services:
  flask:
    image: openrave-flask
    container_name: or_flask
    environment:
      UPLOAD_FOLDER: "/opt/openrave-flask/upload"
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017/"
    ports:
      - "8080:5000"
    volumes:
      - ./data/openrave-flask/upload:/opt/openrave-flask/upload
      - ./data/openrave-flask/test-upload:/opt/openrave-flask/test-upload
  mongo:
    image: mongo
    container_name: or_mongo
    volumes:
      - ./log/mongodb:/var/log/mongodb
      - ./data/mongodb:/data/db
